version: '2'
services:
  tomcat:
    image: tomcat:7.0
    ports:
     - "8080:8080"
     - "8000:8000"
    volumes:
     - ./web:/usr/local/tomcat/webapps/ROOT
     - ${HOME}/.jrebel:/root/.jrebel
    # env_file: .env
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
    command: catalina.sh jpda run
    environment:
      JAVA_OPTS: >
       -Ddatabase.jdbcUrl=jdbc:mysql://mysql/vw-vendascorp-local?useSSL=false
       -Ddatabase.credential.user=vw-feirao
       -Ddatabase.credential.password=vw-feirao
       -Dcluster-master=true
    mongodb:
        image: mongo
        container_name: mongodb
        environment:
            MONGO_INITDB_DATABASE: cummutedb
        #    MONGO_INITDB_ROOT_USERNAME: root
        #    MONGO_INITDB_ROOT_PASSWORD: example
        ports:
            - '27017:27017'
        volumes:
            #- '/data/db'
            - './data/monbodb:/data/db'
        networks: 
            - commute-network

    nginx:
        build:
            dockerfile: ./docker/nginx.dockerfile
            context: .
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        networks: 
            - commute-network
    node:
        build:
            dockerfile: ./docker/node-api.dockerfile
            context: .
        container_name: node-api
        ports:
            - "3000:3000"
        networks: 
            - commute-network
        depends_on: 
            - "mongodb"
            - "nginx"

networks: 
    commute-network:
        driver: bridge
