version: '2'
services:
    mongodb:
        image: mongo
        container_name: mongodb
        environment:
            MONGO_INITDB_DATABASE: geolocdb
        #    MONGO_INITDB_ROOT_USERNAME: root
        #    MONGO_INITDB_ROOT_PASSWORD: example
        ports:
            - '27017:27017'
        volumes:
            #- '/data/db'
            - './data/monbodb:/data/db'
        networks: 
            - commute-network
    node:
        build:
            dockerfile: ./docker/node-api.dockerfile
            context: .
        container_name: node-api
        ports:
            - "8088:3000"
        networks: 
            - commute-network
        depends_on:
            - "mongodb"

networks: 
    commute-network:
        driver: bridge
