version: '2'
services:
    nginx:
        build:
            dockerfile: ./docker/nginx.dockerfile
            context: .
        container_name: nginx
        ports:
            - "80:80"
    node:
        build:
            dockerfile: ./docker/node-api.dockerfile
            context: .
        container_name: node
        ports:
            - "3000:3000"
          